groups:
- name: Instances
  rules:
  - alert: InstanceDown
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.'
      summary: 'Instance {{ $labels.instance }} down'
  - alert: HostOutOfMemory
    expr: wmi_os_physical_memory_free_bytes < 1675512832
    for: 10s
    labels:
      severity: warning
    annotations:
            #summary: "Host out of memory (instance {{ $labels.instance }})" 
            # description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      summary: "Het Ram may (instance {{ $labels.instance }})"
      description: "Thua"
  - alert: Httperror
    expr: probe_http_status_code != 200
    for: 10s
    labels:
      severity: warning
    annotations:
            #summary: "Host out of memory (instance {{ $labels.instance }})"
            # description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      summary: "Service web down(instance {{ $labels.instance }})"
      description: "rot web " 

  - alert: HostOutOfDiskSpace
    expr: (node_filesystem_avail{mountpoint="/"}  * 100) / node_filesystem_size{mountpoint="/"} < 50
    for: 1s
    labels:
      severity: warning
    annotations:
      summary: "Host out of disk space (instance {{ $labels.instance }})"
      description: "Disk is almost full (< 50% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"


  - alert: HostHighCpuLoad
    expr: (sum by (instance) (irate(node_cpu{job="node_exporter_metrics",mode="idle"}[5m]))) > 80
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Host high CPU load (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  - alert: Camera
    expr: max(probe_icmp_duration_seconds{phase="rtt"}) by (hostname) > 0 and avg(probe_http_status_code{}) by ( hostname ) != 200
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Camera down  (instance {{ $labels.instance }})"
      description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
