apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.prometheus.name }}
  namespace: default
spec:
  rules:
  - host: jack.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
             name: {{ .Values.prometheus.service }}
             port:
               number: {{ .Values.prometheus.port }}

