apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service }} 
spec:
  selector: {{ include "common.labels" . | nindent 6 }}
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      
